---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whois
  namespace: applications
  labels:
    k8s-app: whois
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: whois
  template:
    metadata:
      labels:
        k8s-app: whois
        name: whois
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: msfidelis/whois:v1
        name: whois
        ports:
        - name: http
          containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: whois
  namespace: applications
spec:
  selector:
    k8s-app: whois
  ports:
    - protocol: TCP
      port: 80
      name: web
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: k8s.raj.ninja
    http:
      paths:
      - path: /whois
        backend:
          serviceName: whois
          servicePort: 8080