---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: faker
  labels:
    k8s-app: faker
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: faker
  template:
    metadata:
      labels:
        k8s-app: faker
        name: faker
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: msfidelis/faker:v1
        name: faker
        ports:
        - name: http
          containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: faker
spec:
  selector:
    k8s-app: faker
  ports:
    - protocol: TCP
      port: 5000
      name: web
  type: NodePort