---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: pudim
  labels:
    k8s-app: pudim
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: pudim
  template:
    metadata:
      labels:
        k8s-app: pudim
        name: pudim
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: msfidelis/pudim:v0
        name: pudim
        ports:
        - name: http
          containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: pudim
spec:
  selector:
    k8s-app: pudim
  ports:
    - protocol: TCP
      port: 80
      name: web
  type: NodePort